<a href="https://colab.research.google.com/github/HarshTikone/Numpy-Basics/blob/main/Welcome_To_Colaboratory.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

IMPORTING NUMPY IN PYTHON NOTEBOOK

In [1]:
import numpy as np

CHECKING THE VERSION OF NUMPY

In [2]:
np.__version__

'1.22.4'

BASIC WAY TO CREATE AN ARRAY

In [5]:
r1 = [1,2,3]
r2 = [4,5,6]
r3 = [7,8,9]

mat1 = np.array([r1,r2,r3])
print(mat1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


CREATIG A MATRIX USING EMPTY AND RANDOM INPUT VALUES

In [12]:
mat1 = np.empty([2,2], dtype = int)
print(mat1)

[[    101615943253178                   0]
 [8029390848441480559 6998704207589941364]]


CREATIG A MATRIX USING RANDOM and RANDINT AND RANDOM INPUT VALUES

In [10]:
np.random.randint(0, 20, (15, 15))

array([[12, 14,  8, 19, 13,  2,  0, 18, 16, 16,  0, 15, 15, 14, 13],
       [ 9,  2, 14, 11, 10, 15,  3,  6, 11,  4,  0, 16,  1, 11, 13],
       [ 8,  6, 17,  5, 12, 14, 10, 19, 12, 11,  6,  1, 13,  9, 14],
       [ 7,  4, 17,  4, 19,  7, 15,  5, 17, 11,  1,  1,  5, 18, 13],
       [10, 10,  7,  6,  7,  7,  8, 16,  0,  9,  9, 18, 18,  8, 15],
       [ 8,  7,  9,  4,  6, 14, 18,  0,  7,  6, 17, 12, 11, 16, 13],
       [ 5,  7,  9, 19, 12, 10, 16, 13, 15,  7,  3, 11,  6, 14, 15],
       [18, 16, 12,  0,  6,  3,  9, 14, 14,  3, 10,  7,  3,  2,  8],
       [16,  5,  5,  1, 11, 12,  8,  5,  2,  8,  1, 14,  8,  9,  5],
       [ 2,  2,  0, 10,  7, 14, 14, 17, 16,  7, 12,  1,  5, 19, 18],
       [ 2,  8, 13, 19,  7,  9, 12, 11, 10,  7, 10,  4, 13, 17, 13],
       [19,  7,  4,  5,  5,  7, 15,  2,  2, 18, 18, 13, 10, 14,  1],
       [ 4, 15,  9,  0, 19,  9, 13,  8, 11,  2, 15,  1,  7,  3,  5],
       [10,  0,  4, 15,  9, 12, 10, 15, 17, 15,  3, 12, 12,  2,  0],
       [18,  5, 14,  3,  8,  3,  1

CREATIG A NULL MATRIX OR VECTOR USING ZEROS

In [14]:
x = np.zeros(20,dtype= int)
x[15] = 79
print(x)

[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 79  0  0  0  0]


REVERSING AN ARRAY BY USING FLIP

In [16]:
arr = np.array([1,2,3,4,5,6,7,8])
print(np.flip(arr))

[8 7 6 5 4 3 2 1]


DISPLAYING 30 DAYS OF JULY

In [21]:
print(np.arange('2023-07-01', '2023-07-31',
                dtype='datetime64[D]'))

['2023-07-01' '2023-07-02' '2023-07-03' '2023-07-04' '2023-07-05'
 '2023-07-06' '2023-07-07' '2023-07-08' '2023-07-09' '2023-07-10'
 '2023-07-11' '2023-07-12' '2023-07-13' '2023-07-14' '2023-07-15'
 '2023-07-16' '2023-07-17' '2023-07-18' '2023-07-19' '2023-07-20'
 '2023-07-21' '2023-07-22' '2023-07-23' '2023-07-24' '2023-07-25'
 '2023-07-26' '2023-07-27' '2023-07-28' '2023-07-29' '2023-07-30']


CREATING 1 BORDER and 0 INSIDE MATRIX

In [39]:
x = np.ones((5,5), dtype = int)
x[1:-1,1:-1] = 0
print(x)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


USING MATRIX FUNCTION USING NUMPY

In [60]:
a = np.random.randint(0,10, (2, 2))

b = np.random.randint(0,10, (2, 2))
print("A Matrix : ")
print(a)
print("B Matrix : ")
print(b)
result = np.add(a,b)
print("Add Matrix : ")
print(result)
result = np.subtract(a,b)
print("Subtract Matrix : ")
print(result)
result = np.multiply(a,b)
print("A Matrix : ")
print(result)

[[5 5]
 [5 1]]

[[9 4]
 [9 7]]

[[14  9]
 [14  8]]

[[-4  1]
 [-4 -6]]

[[45 20]
 [45  7]]


GENERATING 6 RANDOM INTEGERS BETWEEN 20 to 40

In [52]:
a = np.random.randint(20,40,(6))
for i in  a :
  print(i)

39
32
25
33
30
36


RANDOMLY CREATING 5 X 5 MATRIX WITH ITS MAX AND MIN VALUE

In [54]:
a = np.random.randint(0 , 100 , (5 , 5))
print(a)

print(a.min())
print(a.max())

[[53  4 64 22 12]
 [92 39  4 57 74]
 [34 65 90 13 68]
 [76 12  2 53 13]
 [71 12 20  2 22]]
2
92


NORMALIZING THE ANY 2d MATRIX

In [59]:
def normalize_2d(matrix):
    norm = np.linalg.norm(matrix)
    matrix = matrix/norm
    return matrix

arr = np.random.randint(0 , 10 , (3 , 3))
nor_arr = normalize_2d(arr)

print(arr)
print(nor_arr)


[[0 6 5]
 [8 3 2]
 [3 7 0]]
[[0.         0.42857143 0.35714286]
 [0.57142857 0.21428571 0.14285714]
 [0.21428571 0.5        0.        ]]
